sudo: required
language: ruby

services:
  - docker

install: true

script:
  - docker build -t olhtbr/metadata-resource:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push olhtbr/metadata-resource:latest;
      docker tag olhtbr/metadata-resource:latest olhtbr/metadata-resource:2.0.1;
      docker push olhtbr/metadata-resource:2.0.1;
    fi
